#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/advan/X1

PRODUCT_COPY_FILES += \
    vendor/advan/X1/proprietary/system/etc/public.libraries-mtk.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/public.libraries-mtk.txt \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.drbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/020f0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/020f0000000000000000000000000000.tlbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/035c0000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/035c0000000000000000000000000000.drbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/035c0000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/035c0000000000000000000000000000.tlbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/05060000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05060000000000000000000000000000.tabin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/05070000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05070000000000000000000000000000.drbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.drbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/05120000000000000000000000000001.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/05120000000000000000000000000001.tlbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.drbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/06090000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/06090000000000000000000000000000.tlbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/0706000000000000000000000000004d.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/0706000000000000000000000000004d.tlbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/07061000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07061000000000000000000000000000.tlbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.drbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/07150000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07150000000000000000000000000000.tlbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.drbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/07170000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07170000000000000000000000000000.tlbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/08030000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08030000000000000000000000000000.tabin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/08040000000000000000000000003419.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08040000000000000000000000003419.tabin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.drbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/08050000000000000000000000003419.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08050000000000000000000000003419.tlbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/08110000000000000000000000000000.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/08110000000000000000000000000000.tabin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.drbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/40188311faf343488db888ad39496f9a.tlbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.drbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.drbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/5020170115e016302017012521300000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/5020170115e016302017012521300000.tlbin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/8b22aba81ef0ccbfd9f5f4b634127e15.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/8b22aba81ef0ccbfd9f5f4b634127e15.tabin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/abcd270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/advan/X1/proprietary/vendor/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/e97c270ea5c44c58bcd3384a2fa2539e.tabin \
    vendor/advan/X1/proprietary/vendor/etc/BSTAISCENE:$(TARGET_COPY_OUT_VENDOR)/etc/BSTAISCENE \
    vendor/advan/X1/proprietary/vendor/etc/BSTAI_HDR:$(TARGET_COPY_OUT_VENDOR)/etc/BSTAI_HDR \
    vendor/advan/X1/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/advan/X1/proprietary/vendor/etc/aibokeh_BSTAI_preview:$(TARGET_COPY_OUT_VENDOR)/etc/aibokeh_BSTAI_preview \
    vendor/advan/X1/proprietary/vendor/etc/aibokeh_BSTAI_still:$(TARGET_COPY_OUT_VENDOR)/etc/aibokeh_BSTAI_still \
    vendor/advan/X1/proprietary/vendor/etc/apdb/APDB_MT6789___W2422:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6789___W2422 \
    vendor/advan/X1/proprietary/vendor/etc/apdb/APDB_MT6789___W2422_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6789___W2422_ENUM \
    vendor/advan/X1/proprietary/vendor/etc/armnn_app.config:$(TARGET_COPY_OUT_VENDOR)/etc/armnn_app.config \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/AudioParamOptions_mgvi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_mgvi.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/AudioParamOptions_vext.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamOptions_vext.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/AudioParamVersionInfo.txt:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/AudioParamVersionInfo.txt \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/CRSVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/CRSVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVolUI_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/CRSVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/CRSVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/CRSVol_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/preset_default.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_default.bin \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/preset_music.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_music.bin \
    vendor/advan/X1/proprietary/vendor/etc/audio_param/preset_voip.bin:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/preset_voip.bin \
    vendor/advan/X1/proprietary/vendor/etc/bst_3ddns_front.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bst_3ddns_front.cfg \
    vendor/advan/X1/proprietary/vendor/etc/bst_3ddns_macro.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bst_3ddns_macro.cfg \
    vendor/advan/X1/proprietary/vendor/etc/bst_3ddns_main.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bst_3ddns_main.cfg \
    vendor/advan/X1/proprietary/vendor/etc/bst_3ddns_user_front.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bst_3ddns_user_front.cfg \
    vendor/advan/X1/proprietary/vendor/etc/bst_3ddns_user_macro.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bst_3ddns_user_macro.cfg \
    vendor/advan/X1/proprietary/vendor/etc/bst_3ddns_user_main.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bst_3ddns_user_main.cfg \
    vendor/advan/X1/proprietary/vendor/etc/bst_3ddns_user_wide.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bst_3ddns_user_wide.cfg \
    vendor/advan/X1/proprietary/vendor/etc/bst_3ddns_wide.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bst_3ddns_wide.cfg \
    vendor/advan/X1/proprietary/vendor/etc/bst_aibokeh.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bst_aibokeh.cfg \
    vendor/advan/X1/proprietary/vendor/etc/bst_face_unlock/bstFaceUnlock.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bst_face_unlock/bstFaceUnlock.cfg \
    vendor/advan/X1/proprietary/vendor/etc/bst_filter_config.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bst_filter_config.cfg \
    vendor/advan/X1/proprietary/vendor/etc/bstbeauty.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/bstbeauty.cfg \
    vendor/advan/X1/proprietary/vendor/etc/control_param_AiScene_encode.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/control_param_AiScene_encode.cfg \
    vendor/advan/X1/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/advan/X1/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/advan/X1/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/advan/X1/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/advan/X1/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/advan/X1/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/advan/X1/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/advan/X1/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/advan/X1/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/advan/X1/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/advan/X1/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/advan/X1/proprietary/vendor/etc/init/android.hardware.drm@1.4-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.4-service.widevine.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/android.hardware.gnss-service.mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss-service.mediatek.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.graphics.allocator@4.0-service-mediatek.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/android.hardware.media.c2@1.2-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.media.c2@1.2-mediatek.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks-shim-service-mtk.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.secure_element@1.2-service-mediatek.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/android.hardware.security.keymint-service.trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service.trustonic.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/camerahalserver.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/camerahalserver.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/chipinfo_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/chipinfo_init.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/fuelgauged_nvram_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_nvram_init.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/hw/init.stnfc.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.stnfc.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/init.connfem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.connfem.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/init.gps_pwr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_pwr.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/init.thermal_core.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_core.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/init.vtservice_hidl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vtservice_hidl.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/init.wmt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wmt_drv.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/nvram_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/nvram_daemon.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/tee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tee.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/tetheroffloadservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/tetheroffloadservice.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/trustonic.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/trustonic.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/v3avpud.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/v3avpud.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.keymaster_attestation@1.1-service.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mmagent@1.1-service.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.mms@1.6-service.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.nvram@1.1-sevice.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.mediatek.hardware.pq@2.2-service.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/vendor.trustonic.tee@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.1-service.rc \
    vendor/advan/X1/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/advan/X1/proprietary/vendor/etc/libnfc-hal-st.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-hal-st.conf \
    vendor/advan/X1/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/advan/X1/proprietary/vendor/etc/meow.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/meow.cfg \
    vendor/advan/X1/proprietary/vendor/etc/mpe.conf:$(TARGET_COPY_OUT_VENDOR)/etc/mpe.conf \
    vendor/advan/X1/proprietary/vendor/etc/nnapi_powerhal.json:$(TARGET_COPY_OUT_VENDOR)/etc/nnapi_powerhal.json \
    vendor/advan/X1/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/advan/X1/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-extended-seccomp-policy \
    vendor/advan/X1/proprietary/vendor/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/android.hardware.media.c2@1.2-mediatek-seccomp-policy \
    vendor/advan/X1/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/advan/X1/proprietary/vendor/etc/smsdbvisitor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/smsdbvisitor.xml \
    vendor/advan/X1/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/advan/X1/proprietary/vendor/etc/st21nfc_conf.txt:$(TARGET_COPY_OUT_VENDOR)/etc/st21nfc_conf.txt \
    vendor/advan/X1/proprietary/vendor/etc/task_profiles.json:$(TARGET_COPY_OUT_VENDOR)/etc/task_profiles.json \
    vendor/advan/X1/proprietary/vendor/etc/thermal/disable_skin_control.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_skin_control.conf \
    vendor/advan/X1/proprietary/vendor/etc/thermal/disable_thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal.conf \
    vendor/advan/X1/proprietary/vendor/etc/thermal/disable_thermal_temp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_thermal_temp.conf \
    vendor/advan/X1/proprietary/vendor/etc/thermal/disable_throttling.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/disable_throttling.conf \
    vendor/advan/X1/proprietary/vendor/etc/thermal/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal.conf \
    vendor/advan/X1/proprietary/vendor/etc/thermal/thermal_mtbf.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_mtbf.conf \
    vendor/advan/X1/proprietary/vendor/etc/thermal/thermal_policy_00.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_00.conf \
    vendor/advan/X1/proprietary/vendor/etc/thermal/thermal_policy_02.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_02.conf \
    vendor/advan/X1/proprietary/vendor/etc/thermal/thermal_policy_08.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal/thermal_policy_08.conf \
    vendor/advan/X1/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/advan/X1/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/advan/X1/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/advan/X1/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/advan/X1/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/advan/X1/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/advan/X1/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1d_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1d_1.bin \
    vendor/advan/X1/proprietary/vendor/firmware/WIFI_RAM_CODE_soc2_2_1e_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc2_2_1e_1.bin \
    vendor/advan/X1/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/advan/X1/proprietary/vendor/firmware/fs1599.fsm:$(TARGET_COPY_OUT_VENDOR)/firmware/fs1599.fsm \
    vendor/advan/X1/proprietary/vendor/firmware/lib3a.ccu:$(TARGET_COPY_OUT_VENDOR)/firmware/lib3a.ccu \
    vendor/advan/X1/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/advan/X1/proprietary/vendor/firmware/soc2_2_ram_bt_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1d_1_hdr.bin \
    vendor/advan/X1/proprietary/vendor/firmware/soc2_2_ram_bt_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_bt_1e_1_hdr.bin \
    vendor/advan/X1/proprietary/vendor/firmware/soc2_2_ram_mcu_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1d_1_hdr.bin \
    vendor/advan/X1/proprietary/vendor/firmware/soc2_2_ram_mcu_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_mcu_1e_1_hdr.bin \
    vendor/advan/X1/proprietary/vendor/firmware/soc2_2_ram_wifi_1d_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1d_1_hdr.bin \
    vendor/advan/X1/proprietary/vendor/firmware/soc2_2_ram_wifi_1e_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc2_2_ram_wifi_1e_1_hdr.bin \
    vendor/advan/X1/proprietary/vendor/firmware/st21nfc_fw7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/st21nfc_fw7.bin \
    vendor/advan/X1/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg

PRODUCT_PACKAGES += \
    libaedv \
    libbwc \
    libcares_naptr \
    libccci_util \
    libgz_gp_client \
    libgz_uree \
    libhevce_sb.ca7.android \
    libion_mtk \
    libion_ulit \
    libladder \
    libmtkares \
    libmtkcutils \
    libmtkhardware_legacy \
    libmtknetutils \
    libmtkproperty \
    libmtkrillog \
    libmtksysutils \
    libsysenv \
    libthha \
    libvcodec_oal \
    libvcodecdrv_header_stub \
    libmtk_drvb \
    libHEVCdec_sa.ca7.android \
    libh264dec_customize \
    libh264dec_sa.ca7 \
    libh264dec_sd.ca7 \
    libh264dec_se.ca7 \
    libmp4enc_sa.ca7 \
    libvcodec_utility_plat.mt6789 \
    libvp8dec_sa.ca7 \
    libvp8enc_sa.ca7 \
    libvp9dec_sa.ca7 \
    libvcodec_utility \
    libvcodec_utility_v3a \
    libvcodecdrv \
    libvcodecdrv_v3a \
    libvpudv3a_vcodec \
    APUWareApusysServer \
    APUWareHmpServer \
    APUWareUtilsServer \
    libGLES_meow \
    libMEOW_data \
    libMEOW_gift \
    libMEOW_qt \
    libMEOW_trace \
    libGLES_mali \
    android.hardware.gnss-impl-mediatek \
    android.hardware.gnss@2.1-impl-mediatek \
    audio.primary.mediatek \
    fingerprint.mt6789 \
    gps.default \
    hwcomposer.mtk_common \
    kmsetkey.trustonic \
    libMcGatekeeper \
    libSoftGatekeeper \
    android.hardware.camera.provider@2.6-impl-mediatek \
    android.hardware.graphics.allocator@4.0-impl-mediatek \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    gralloc.common \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    vendor.mediatek.hardware.camera.bgservice@1.1-impl \
    vendor.mediatek.hardware.camera.ccap@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.0-impl \
    vendor.mediatek.hardware.camera.isphal@1.1-impl \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.mediatek.hardware.pq@2.15-impl \
    vulkan.mali \
    sensors.mediatek.V2.0 \
    sound_trigger.primary.mt6789 \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.mediatek.hardware.nvram@1.1-impl \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    libAcceReader \
    libAlgoUtils \
    libBST3DDNS \
    libBSTAiScene \
    libBSTBeauty \
    libBSTHDRDETECT \
    libBSTMultiExpoGainHDR \
    libBSTSingleAIBokeh \
    libBstFaceUlkImpl \
    libCamera_gc08a3sub2lanemipiraw_Scene_Capture_HDR \
    libCamera_gc08a3sub2lanemipiraw_Scene_Preview_HDR \
    libCamera_imx782mipiraw_Coosea_Remosaic \
    libCamera_imx782mipiraw_Scene_HDR \
    libCamera_imx782mipiraw_Scene_lowlight \
    libCamera_imx782mipiraw_Scene_singleFrame \
    libCamera_imx782mipiraw_Video_1080_120 \
    libCamera_imx782mipiraw_Video_Zoom_2x \
    libDefaultFpsActor \
    libFrameRecord \
    libHDRDetectUtils \
    libHDRUtils \
    libJpgEncPipe \
    libMcClient \
    libMtkSpeechEnh \
    libNoFpsActor \
    libOpenCL \
    libSQLiteModule_VER_ALL \
    libSingleAIBokehUtils \
    libTEECommon \
    lib_iir \
    lib_speech_enh \
    libaal_cust \
    libaal_key \
    libaal_mtk \
    libalsautils-v31 \
    libapu_mdw \
    libapu_mdw_batch \
    libapusys \
    libapusys_edma \
    libarmnn \
    libarmnn_ndk.mtk.vndk \
    libasn1c_core \
    libaudio_param_parser-vnd \
    libaudiocompensationfilter_vendor \
    libaudiocompensationfilterc \
    libaudiocomponentengine_vendor \
    libaudiocomponentenginec \
    libaudiocustparam_vendor \
    libaudiodcrflt_vendor \
    libaudiofmtconv \
    libaudioloudc \
    libaudioprimarydevicehalifclient \
    libaudiosmartpamtk \
    libaudiotoolkit_vendor \
    libaurisysdemo \
    libbessound_hd_mtk_vendor \
    libblisrc32_vendor \
    libbluetooth_mtk \
    libbluetooth_mtk_pure \
    libbstFaceUnlock \
    libbstFilterCapture \
    libbst_beauty_algoutils \
    libbstfaceid_ca \
    libbt-vendor \
    libcam.seninfn3d \
    libcamalgo.3dnr \
    libcamalgo.dngop \
    libcamalgo.eis \
    libcamalgo.fdft \
    libcamalgo.fsc \
    libcamalgo.gyro \
    libcamalgo.lmv \
    libcamalgo.n3d \
    libcamalgo.nr \
    libcamalgo.platform \
    libcamalgo.utility \
    libcamalgo.warp \
    libcapctrl \
    libcarrierconfig \
    libcmdl \
    libcmdl_ndk.mtk.vndk \
    libcodec2_hidl@1.0-v33 \
    libcodec2_hidl@1.1-v33 \
    libcodec2_hidl@1.2-v33 \
    libcodec2_hidl_plugin-v33 \
    libcodec2_mtk_c2store \
    libcodec2_mtk_vdec \
    libcodec2_mtk_venc \
    libcodec2_soft_common-v33 \
    libcodec2_vndk-v33 \
    libcodec2_vpp_qt_plugin \
    libcodec2_vpp_rs_plugin \
    libcomposer_ext \
    libconnfem \
    libcustom_nvram \
    libcvsd_mtk \
    libdecrypt \
    libdynamiclog \
    libfgauge_gm30 \
    libfile_op \
    libforkexecwrap \
    libformatter \
    libfsmaudio \
    libged \
    libgf_ca \
    libgf_hal \
    libgoodixhwfingerprint \
    libgpu_aux \
    libgpud \
    libgralloc_extra \
    libgralloc_metadata \
    libgralloctypes_mtk \
    libgwsd-ril \
    libgwsdv2-ril \
    libgwsdv3-ril \
    libhdrvideo \
    libheichal \
    libhfmanager \
    libhfmanagerwrapper \
    libhwm \
    libifcutils_mtk \
    libimagebuffer_wrapper \
    libimgsensorca \
    libispcameraca \
    libjpeg-alpha-oal_vendor \
    libjpeg-alpha_vendor \
    libkmsetkey \
    libksensor \
    libminiui \
    libmipc \
    libmmagent \
    libmml \
    libmnetlink_v104 \
    libmorpho_GroupPhoto \
    libmorpho_MotionSensor \
    libmorpho_Superlowlight \
    libmorpho_superlowlight_algoutils \
    libmsbc_mtk \
    libmtk-fusion-ril-prop-vsim \
    libmtk-ril \
    libmtkcam.plugin.cap.3ddns \
    libmtkcam.plugin.cap.aibokeh \
    libmtkcam.plugin.cap.beauty \
    libmtkcam.plugin.cap.filter \
    libmtkcam.plugin.cap.groupphoto \
    libmtkcam.plugin.cap.hdr \
    libmtkcam.plugin.cap.superlowlight \
    libmtkcam.plugin.prv.aibokeh \
    libmtkcam.plugin.prv.aiscene \
    libmtkcam.plugin.prv.hdrdetect \
    libmtkcam.plugin.prv.motionsensor \
    libmtkcam_pipelinepolicy-aov \
    libmtkconfig \
    libmtkconfigutils \
    libmtkisp_metadata \
    libmtklimiter_vendor \
    libmtkmipc-ril \
    libmtknetcap \
    libmtkrilutils \
    libmtkshifter_vendor \
    libmtkspparser \
    libmtktinyxml \
    libmtkutils \
    libmvpu_cic_ci_compiler \
    libmvpu_clc_cl_compiler \
    libmvpu_clc_mvpu_debuginfo \
    libmvpu_clc_mvpu_elf \
    libmvpu_clc_mvpu_utility \
    libmvpu_clc_vpu_isa \
    libmvpu_config \
    libmvpu_engine \
    libmvpu_engine_pub \
    libmvpu_pattern \
    libmvpu_pattern_pub \
    libmvpu_runtime \
    libmvpu_runtime_pub \
    libmvpuop_mtk_cv \
    libmvpuop_mtk_nn \
    libneuron_graph_delegate.mtk_vendor \
    libneuron_platform \
    libnir_neon_driver_ndk.mtk.vndk \
    libnpagent \
    libnpagent_server \
    libnvram \
    libnvram_sec \
    libnxp_extamp_intf \
    libpixelflinger \
    libpqframework \
    libratconfig \
    libremosaic_wrapper \
    libremosaiclib \
    librgbwlightsensor \
    librilfusion \
    librmsclib1 \
    librpc \
    librt_extamp_intf \
    libsfplugin_ccodec_utils-v33 \
    libspeech_enh_lib \
    libspeechparser_vendor \
    libstagefright_bufferqueue_helper-ap3a \
    libstorage_otp \
    libtensorflowlite \
    libtflite_mtk_vendor \
    libtrm \
    libudf \
    libvendor.goodix.hardware.biometrics.fingerprint@2.1 \
    libverno \
    libvia-ril \
    libviagpsrpc \
    libviamipc-ril \
    libvow_ap_test_aa \
    libvow_ap_test_dd \
    libvow_ap_test_ha \
    libvow_ap_test_hh \
    libvow_ap_test_nn \
    libvpu \
    libwpfa \
    libwvhidl \
    libwvdrmengine \
    arm.graphics-V1-ndk_platform \
    bf2257csmacro_mipi_raw_IdxMgr \
    bf2257csmacro_mipi_raw_tuning \
    gc08a3sub2lane_mipi_raw_IdxMgr \
    gc08a3sub2lane_mipi_raw_tuning \
    gc32e1sub_mipi_raw_IdxMgr \
    gc32e1sub_mipi_raw_tuning \
    imx782_mipi_raw_IdxMgr \
    imx782_mipi_raw_tuning \
    lib3a.ae.core \
    lib3a.ae \
    lib3a.ae.stat \
    lib3a.af.assist \
    lib3a.af.assist.utils \
    lib3a.af.core \
    lib3a.af \
    lib3a.alsflicker \
    lib3a.awb.core \
    lib3a.ccudrv \
    lib3a.ccuif \
    lib3a.custom.ae \
    lib3a.dce \
    lib3a.flash \
    lib3a.flicker \
    lib3a.gma \
    lib3a.lce \
    lib3a.log \
    lib3a.n3d3a \
    lib3a.sensors.color \
    lib3a.sensors.flicker \
    libCamera_bf2257csmacromipiraw_E2EHDR_Preview \
    libCamera_bf2257csmacromipiraw_E2EHDR_Video \
    libCamera_bf2257csmacromipiraw_Face_Capture \
    libCamera_bf2257csmacromipiraw_Flash_Capture \
    libCamera_bf2257csmacromipiraw_HDR_Capture \
    libCamera_bf2257csmacromipiraw_HDR_Preview \
    libCamera_bf2257csmacromipiraw_HDR_Video \
    libCamera_bf2257csmacromipiraw_N3D_Capture \
    libCamera_bf2257csmacromipiraw_N3D_Preview \
    libCamera_bf2257csmacromipiraw_N3D_Video \
    libCamera_bf2257csmacromipiraw_P1_YUV \
    libCamera_bf2257csmacromipiraw_Scene_Capture \
    libCamera_bf2257csmacromipiraw_Scene_Capture_4cell \
    libCamera_bf2257csmacromipiraw_Scene_Preview \
    libCamera_bf2257csmacromipiraw_Scene_Preview_4k \
    libCamera_bf2257csmacromipiraw_Scene_Preview_ZSD_Flash \
    libCamera_bf2257csmacromipiraw_Video_1080 \
    libCamera_bf2257csmacromipiraw_Video_4k \
    libCamera_gc08a3sub2lanemipiraw_E2EHDR_Preview \
    libCamera_gc08a3sub2lanemipiraw_E2EHDR_Video \
    libCamera_gc08a3sub2lanemipiraw_Face_Capture \
    libCamera_gc08a3sub2lanemipiraw_Flash_Capture \
    libCamera_gc08a3sub2lanemipiraw_HDR_Capture \
    libCamera_gc08a3sub2lanemipiraw_HDR_Preview \
    libCamera_gc08a3sub2lanemipiraw_HDR_Video \
    libCamera_gc08a3sub2lanemipiraw_N3D_Capture \
    libCamera_gc08a3sub2lanemipiraw_N3D_Preview \
    libCamera_gc08a3sub2lanemipiraw_N3D_Video \
    libCamera_gc08a3sub2lanemipiraw_P1_YUV \
    libCamera_gc08a3sub2lanemipiraw_Scene_Capture \
    libCamera_gc08a3sub2lanemipiraw_Scene_Capture_4cell \
    libCamera_gc08a3sub2lanemipiraw_Scene_Preview \
    libCamera_gc08a3sub2lanemipiraw_Scene_Preview_4k \
    libCamera_gc08a3sub2lanemipiraw_Scene_Preview_ZSD_Flash \
    libCamera_gc08a3sub2lanemipiraw_Video_1080 \
    libCamera_gc08a3sub2lanemipiraw_Video_4k \
    libCamera_gc32e1submipiraw_E2EHDR_Preview \
    libCamera_gc32e1submipiraw_E2EHDR_Video \
    libCamera_gc32e1submipiraw_Face_Capture \
    libCamera_gc32e1submipiraw_Flash_Capture \
    libCamera_gc32e1submipiraw_HDR_Capture \
    libCamera_gc32e1submipiraw_HDR_Preview \
    libCamera_gc32e1submipiraw_HDR_Video \
    libCamera_gc32e1submipiraw_N3D_Capture \
    libCamera_gc32e1submipiraw_N3D_Preview \
    libCamera_gc32e1submipiraw_N3D_Video \
    libCamera_gc32e1submipiraw_P1_YUV \
    libCamera_gc32e1submipiraw_Scene_Capture \
    libCamera_gc32e1submipiraw_Scene_Capture_4cell \
    libCamera_gc32e1submipiraw_Scene_Preview \
    libCamera_gc32e1submipiraw_Scene_Preview_4k \
    libCamera_gc32e1submipiraw_Scene_Preview_ZSD_Flash \
    libCamera_gc32e1submipiraw_Video_1080 \
    libCamera_gc32e1submipiraw_Video_4k \
    libCamera_imx782mipiraw_E2EHDR_Preview \
    libCamera_imx782mipiraw_E2EHDR_Video \
    libCamera_imx782mipiraw_Face_Capture \
    libCamera_imx782mipiraw_Flash_Capture \
    libCamera_imx782mipiraw_HDR_Capture \
    libCamera_imx782mipiraw_HDR_Preview \
    libCamera_imx782mipiraw_HDR_Reconfig_Preview \
    libCamera_imx782mipiraw_HDR_Reconfig_Video \
    libCamera_imx782mipiraw_HDR_Video \
    libCamera_imx782mipiraw_N3D_Capture \
    libCamera_imx782mipiraw_N3D_Preview \
    libCamera_imx782mipiraw_N3D_Video \
    libCamera_imx782mipiraw_P1_YUV \
    libCamera_imx782mipiraw_Scene_Capture \
    libCamera_imx782mipiraw_Scene_Capture_4cell \
    libCamera_imx782mipiraw_Scene_Preview \
    libCamera_imx782mipiraw_Scene_Preview_4k \
    libCamera_imx782mipiraw_Scene_Preview_ZSD_Flash \
    libCamera_imx782mipiraw_Video_1080 \
    libCamera_imx782mipiraw_Video_1080_60 \
    libCamera_imx782mipiraw_Video_4k \
    libDR \
    libSonyIMX230PdafLibrary \
    libSonyIMX230PdafLibraryWrapper \
    libSonyIMX338PdafLibrary \
    libSonyIMX338PdafLibraryWrapper \
    libSonyIMX386PdafLibrary \
    libSonyIMX386PdafLibraryWrapper \
    libSonyIMX519PdafLibrary \
    libSonyIMX519PdafLibraryWrapper \
    libaaa_ltm \
    libaaa_ltmx \
    libaal_cust_func \
    libaalservice \
    libacdk \
    libaiawb_moon \
    libaiawb_p1ggm \
    libaiawb_sun \
    libaibc_tuning \
    libaibc_tuning_p2 \
    libaibc_tuning_p3 \
    libaibc_tuning_p4 \
    libaidepth_tuning \
    libaiselector \
    libcam.afhal \
    libcam.chdr \
    libcam.feature_utils \
    libcam.hal3a.cctsvr \
    libcam.hal3a.log \
    libcam.hal3a.v3.ae \
    libcam.hal3a.v3.ai3a \
    libcam.hal3a.v3.awb \
    libcam.hal3a.v3.dng \
    libcam.hal3a.v3.fsmgr \
    libcam.hal3a.v3.lscMgr \
    libcam.hal3a.v3.lsctbl.50 \
    libcam.hal3a.v3.nvram.50 \
    libcam.hal3a.v3.platform \
    libcam.hal3a.v3.resultpool \
    libcam.hal3a.v3 \
    libcam.halisp.buf \
    libcam.halisp.common \
    libcam.halisp \
    libcam.halsensor.hwintegration \
    libcam.halsensor \
    libcam.iopipe \
    libcam.isptuning \
    libcam.pdtblgen \
    libcam.tuning.cache \
    libcam.utils.sensorprovider \
    libcam.vhdr \
    libcamalgo.ispfeature \
    libcamalgo.lsc \
    libcamalgo.platform2 \
    libcamalgo.rotate \
    libcamalgo.vsf \
    libcamdrv_isp \
    libcamdrv_tuning_mgr \
    libcamdrv_twin \
    libcamera.custom.pd_buf_mgr \
    libcamera.customae \
    libcamera.customaf \
    libcamera.customawb \
    libcamera.customflk \
    libcameracustom.camera.3a \
    libcameracustom.camera.isp \
    libcameracustom.camera.sensors \
    libcameracustom.camera_exif \
    libcameracustom.eis \
    libcameracustom.flashlight \
    libcameracustom.lens \
    libcameracustom.plugin \
    libcameracustom \
    libdip_drv \
    libdip_postproc \
    libdpframework \
    libeffecthal.base \
    libfeature.face \
    libfeature.stereo.provider \
    libfeature.vsdof.hal \
    libfeature_3dnr \
    libfeature_eis \
    libfeature_fsc \
    libfeature_lmv \
    libfeature_rss \
    libfeatureiodrv_mem \
    libgpudataproducer \
    libimageio \
    libimageio_plat_drv \
    libimageio_plat_pipe \
    liblpcnr \
    libmnl \
    libmsnr \
    libmtkcam.atmseventmgr \
    libmtkcam.eventcallback \
    libmtkcam.featurepipe.capture \
    libmtkcam.featurepipe.depthmap \
    libmtkcam.featurepipe.streaming \
    libmtkcam.featurepipe.vsdof_util \
    libmtkcam.logicalmodule \
    libmtkcam_3rdparty.core \
    libmtkcam_3rdparty.customer \
    libmtkcam_3rdparty.mtk \
    libmtkcam_3rdparty \
    libmtkcam_calibration_convertor \
    libmtkcam_calibration_provider \
    libmtkcam_debugutils \
    libmtkcam_device3_app \
    libmtkcam_device3_hal \
    libmtkcam_device3_hidl \
    libmtkcam_device3_hidlutils \
    libmtkcam_device3_utils \
    libmtkcam_devicesessionpolicy \
    libmtkcam_diputils \
    libmtkcam_exif \
    libmtkcam_fdvt \
    libmtkcam_featurepolicy \
    libmtkcam_featureutils \
    libmtkcam_fwkutils \
    libmtkcam_grallocutils \
    libmtkcam_hwnode \
    libmtkcam_hwutils \
    libmtkcam_imem \
    libmtkcam_imgbuf \
    libmtkcam_mapping_mgr \
    libmtkcam_metadata \
    libmtkcam_metastore \
    libmtkcam_mfb \
    libmtkcam_modulefactory_aaa \
    libmtkcam_modulefactory_custom \
    libmtkcam_modulefactory_drv \
    libmtkcam_modulefactory_utils \
    libmtkcam_modulehelper \
    libmtkcam_owe \
    libmtkcam_pipeline \
    libmtkcam_pipeline_fbm \
    libmtkcam_pipelinemodel \
    libmtkcam_pipelinemodel_adapter \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipelinemodel_isp \
    libmtkcam_pipelinemodel_session \
    libmtkcam_pipelinemodel_utils \
    libmtkcam_pipelinemodel_zsl \
    libmtkcam_pipelinepolicy-security \
    libmtkcam_pipelinepolicy-smvr \
    libmtkcam_pipelinepolicy \
    libmtkcam_pipelinepolicy_factory \
    libmtkcam_prerelease \
    libmtkcam_rsc \
    libmtkcam_scenariorecorder \
    libmtkcam_stdutils \
    libmtkcam_streamutils \
    libmtkcam_synchelper \
    libmtkcam_sysutils \
    libmtkcam_tuning_utils \
    libmtkcam_ulog \
    libneuralnetworks_sl_driver_mtk_prebuilt \
    libneuron_adapter_mgvi \
    libneuron_runtime.5 \
    libnir_neon_driver \
    libpq_cust_base \
    libpq_prot \
    libpqparamparser \
    libstereoinfoaccessor_vsdof \
    libvainr_model \
    libmtkcam_streaminfo_plugin-p1stt \
    nfc_nci.st21nfc.st \
    vendor.mediatek.hardware.apuware.apusys@2.0_vendor \
    vendor.mediatek.hardware.apuware.apusys@2.1_vendor \
    vendor.mediatek.hardware.apuware.hmp@1.0_vendor \
    vendor.mediatek.hardware.apuware.utils@2.0_vendor \
    vendor.mediatek.hardware.audio@6.1 \
    vendor.mediatek.hardware.audio@7.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    vendor.mediatek.hardware.camera.atms@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.0 \
    vendor.mediatek.hardware.camera.bgservice@1.1 \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    vendor.mediatek.hardware.camera.security@1.0 \
    vendor.mediatek.hardware.composer_ext@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    vendor.mediatek.hardware.mmagent@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mms@1.1 \
    vendor.mediatek.hardware.mms@1.2 \
    vendor.mediatek.hardware.mms@1.3 \
    vendor.mediatek.hardware.mms@1.4 \
    vendor.mediatek.hardware.mms@1.5 \
    vendor.mediatek.hardware.mms@1.6 \
    vendor.mediatek.hardware.mtkradioex@2.0 \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    vendor.mediatek.hardware.netdagent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.0 \
    vendor.mediatek.hardware.neuropilot.agent@1.1 \
    vendor.mediatek.hardware.neuropilot.agent@1.2 \
    vendor.mediatek.hardware.nvram@1.0 \
    vendor.mediatek.hardware.nvram@1.1 \
    vendor.mediatek.hardware.power@1.1 \
    vendor.mediatek.hardware.power@2.0 \
    vendor.mediatek.hardware.pq@2.0 \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.pq@2.10 \
    vendor.mediatek.hardware.pq@2.11 \
    vendor.mediatek.hardware.pq@2.12 \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.pq@2.15 \
    vendor.mediatek.hardware.pq@2.2 \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.pq@2.4 \
    vendor.mediatek.hardware.pq@2.5 \
    vendor.mediatek.hardware.pq@2.6 \
    vendor.mediatek.hardware.pq@2.7 \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    vendor.mediatek.hardware.videotelephony@1.0 \
    vendor.trustonic.tee.tui@1.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.tee@1.1 \
    libapuwareapusys.mtk \
    libapuwareapusys_v2.mtk \
    libapuwarehmp.mtk \
    libapuwareutils.mtk \
    libapuwareutils_v2.mtk \
    libapuwarexrp.mtk \
    libapuwarexrp_v2.mtk \
    libarmnn_ndk.mtk \
    libcmdl_ndk.mtk \
    libmvpu_cic_ci_compiler.mtk \
    libmvpu_cic_ci_compiler_25.mtk \
    libmvpu_clc_14_mvpu_elf_25.mtk \
    libmvpu_clc_mvpu_elf.mtk \
    libmvpu_config.mtk \
    libmvpu_engine.mtk \
    libmvpu_engine_25.mtk \
    libmvpu_engine_25_pub.mtk \
    libmvpu_engine_pub.mtk \
    libmvpu_pattern.mtk \
    libmvpu_pattern_25.mtk \
    libmvpu_pattern_25_pub.mtk \
    libmvpu_pattern_pub.mtk \
    libmvpu_runtime.mtk \
    libmvpu_runtime_25.mtk \
    libmvpu_runtime_25_pub.mtk \
    libmvpu_runtime_builtin.mtk \
    libmvpu_runtime_builtin_25.mtk \
    libmvpu_runtime_pub.mtk \
    libmvpuop25_mtk_cv.mtk \
    libmvpuop25_mtk_nn.mtk \
    libmvpuop_mtk_cv.mtk \
    libmvpuop_mtk_nn.mtk \
    libneuron_graph_delegate.mtk \
    libneuronusdk_adapter.mtk \
    libnir_neon_driver_ndk.mtk \
    libtflite_mtk.mtk \
    vendor.mediatek.hardware.apuware.apusys-V3-ndk \
    vendor.mediatek.hardware.apuware.apusys@1.0 \
    vendor.mediatek.hardware.apuware.apusys@2.0 \
    vendor.mediatek.hardware.apuware.apusys@2.1 \
    vendor.mediatek.hardware.apuware.hmp@1.0 \
    vendor.mediatek.hardware.apuware.utils-V1-ndk \
    vendor.mediatek.hardware.apuware.utils@1.0 \
    vendor.mediatek.hardware.apuware.utils@2.0 \
    vendor.mediatek.hardware.apuware.xrp@1.0 \
    vendor.mediatek.hardware.apuware.xrp@2.0 \
    android.hardware.neuralnetworks-shim-service-mtk.xml \
    android.hardware.security.keymint-service.trustonic.xml \
    android.hardware.security.secureclock-service.trustonic.xml \
    android.hardware.security.sharedsecret-service.trustonic.xml \
    gnss-mtk.xml \
    gnss@2.1-service.xml \
    manifest_android.hardware.drm@1.4-service.widevine.xml \
    manifest_apuware_apusys.xml \
    manifest_apuware_hmp.xml \
    manifest_apuware_utils.xml \
    manifest_cameraprovider.xml \
    manifest_media_c2_V1_2_default.xml \
    ccci_mdinit \
    ccci_rpcd \
    chipinfo \
    conninfra_loader \
    fuelgauged \
    fuelgauged_nvram \
    gsm0710muxd \
    android.hardware.drm@1.4-service.widevine \
    android.hardware.gnss-service.mediatek \
    android.hardware.media.c2@1.2-mediatek-64b \
    android.hardware.neuralnetworks-shim-service-mtk \
    android.hardware.secure_element@1.2-service-mediatek \
    android.hardware.security.keymint-service.trustonic \
    android.hardware.graphics.allocator@4.0-service-mediatek.mt6789 \
    camerahalserver \
    mtkfusionrild \
    tetheroffloadservice \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mmagent@1.1-service \
    vendor.mediatek.hardware.mms@1.6-service \
    vendor.mediatek.hardware.nvram@1.1-service \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.trustonic.tee@1.1-service \
    vtservice_hidl \
    mcDriverDaemon \
    mnld \
    v3avpud.mt6789 \
    mtk_agpsd \
    netdagent \
    nvram_daemon \
    thermal_core \
    thermal_intf \
    wlan_assistant \
    wmt_launcher \
    wmt_loader

PRODUCT_PACKAGES += \
    vendor_bin_hw_android_hardware_graphics_allocator@4_0-service-mediatek \
    vendor_bin_hw_camerahalserver \
    vendor_bin_v3avpud \
    vendor_lib_libmtk_drvb_so \
    vendor_lib_libvcodec_utility_so \
    vendor_lib_libvcodec_utility_v3a_so \
    vendor_lib_libvcodecdrv_so \
    vendor_lib_libvcodecdrv_v3a_so \
    vendor_lib_libvpudv3a_vcodec_so \
    vendor_lib64_egl_libGLES_mali_so \
    vendor_lib64_hw_audio_primary_mt6789_so \
    vendor_lib64_hw_kmsetkey_default_so \
    vendor_lib64_hw_gatekeeper_trustonic_so \
    vendor_lib64_hw_gatekeeper_default_so \
    vendor_lib64_hw_android_hardware_camera_provider@2_6-impl-mediatek_so \
    vendor_lib64_hw_android_hardware_graphics_allocator@4_0-impl-mediatek_so \
    vendor_lib64_hw_android_hardware_graphics_mapper@4_0-impl-mediatek_so \
    vendor_lib64_hw_gralloc_common_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_atms@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_bgservice@1_1-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_ccap@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_isphal@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_isphal@1_1-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_camera_lomoeffect@1_0-impl_so \
    vendor_lib64_hw_vendor_mediatek_hardware_pq@2_15-impl_so \
    vendor_lib64_hw_vulkan_mali_so \
    vendor_lib64_hw_sensors_mt6789_so \
    vendor_lib64_arm_graphics-V1-ndk_platform_so \
    vendor_lib64_bf2257csmacro_mipi_raw_IdxMgr_so \
    vendor_lib64_bf2257csmacro_mipi_raw_tuning_so \
    vendor_lib64_gc08a3sub2lane_mipi_raw_IdxMgr_so \
    vendor_lib64_gc08a3sub2lane_mipi_raw_tuning_so \
    vendor_lib64_gc32e1sub_mipi_raw_IdxMgr_so \
    vendor_lib64_gc32e1sub_mipi_raw_tuning_so \
    vendor_lib64_imx782_mipi_raw_IdxMgr_so \
    vendor_lib64_imx782_mipi_raw_tuning_so \
    vendor_lib64_lib3a_ae_core_so \
    vendor_lib64_lib3a_ae_so \
    vendor_lib64_lib3a_ae_stat_so \
    vendor_lib64_lib3a_af_assist_so \
    vendor_lib64_lib3a_af_assist_utils_so \
    vendor_lib64_lib3a_af_core_so \
    vendor_lib64_lib3a_af_so \
    vendor_lib64_lib3a_alsflicker_so \
    vendor_lib64_lib3a_awb_core_so \
    vendor_lib64_lib3a_ccudrv_so \
    vendor_lib64_lib3a_ccuif_so \
    vendor_lib64_lib3a_custom_ae_so \
    vendor_lib64_lib3a_dce_so \
    vendor_lib64_lib3a_flash_so \
    vendor_lib64_lib3a_flicker_so \
    vendor_lib64_lib3a_gma_so \
    vendor_lib64_lib3a_lce_so \
    vendor_lib64_lib3a_log_so \
    vendor_lib64_lib3a_n3d3a_so \
    vendor_lib64_lib3a_sensors_color_so \
    vendor_lib64_lib3a_sensors_flicker_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_E2EHDR_Preview_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_E2EHDR_Video_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_Face_Capture_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_Flash_Capture_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_HDR_Capture_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_HDR_Preview_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_HDR_Video_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_N3D_Capture_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_N3D_Preview_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_N3D_Video_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_P1_YUV_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_Scene_Capture_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_Scene_Capture_4cell_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_Scene_Preview_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_Scene_Preview_4k_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_Scene_Preview_ZSD_Flash_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_Video_1080_so \
    vendor_lib64_libCamera_bf2257csmacromipiraw_Video_4k_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_E2EHDR_Preview_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_E2EHDR_Video_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_Face_Capture_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_Flash_Capture_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_HDR_Capture_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_HDR_Preview_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_HDR_Video_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_N3D_Capture_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_N3D_Preview_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_N3D_Video_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_P1_YUV_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_Scene_Capture_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_Scene_Capture_4cell_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_Scene_Preview_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_Scene_Preview_4k_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_Scene_Preview_ZSD_Flash_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_Video_1080_so \
    vendor_lib64_libCamera_gc08a3sub2lanemipiraw_Video_4k_so \
    vendor_lib64_libCamera_gc32e1submipiraw_E2EHDR_Preview_so \
    vendor_lib64_libCamera_gc32e1submipiraw_E2EHDR_Video_so \
    vendor_lib64_libCamera_gc32e1submipiraw_Face_Capture_so \
    vendor_lib64_libCamera_gc32e1submipiraw_Flash_Capture_so \
    vendor_lib64_libCamera_gc32e1submipiraw_HDR_Capture_so \
    vendor_lib64_libCamera_gc32e1submipiraw_HDR_Preview_so \
    vendor_lib64_libCamera_gc32e1submipiraw_HDR_Video_so \
    vendor_lib64_libCamera_gc32e1submipiraw_N3D_Capture_so \
    vendor_lib64_libCamera_gc32e1submipiraw_N3D_Preview_so \
    vendor_lib64_libCamera_gc32e1submipiraw_N3D_Video_so \
    vendor_lib64_libCamera_gc32e1submipiraw_P1_YUV_so \
    vendor_lib64_libCamera_gc32e1submipiraw_Scene_Capture_so \
    vendor_lib64_libCamera_gc32e1submipiraw_Scene_Capture_4cell_so \
    vendor_lib64_libCamera_gc32e1submipiraw_Scene_Preview_so \
    vendor_lib64_libCamera_gc32e1submipiraw_Scene_Preview_4k_so \
    vendor_lib64_libCamera_gc32e1submipiraw_Scene_Preview_ZSD_Flash_so \
    vendor_lib64_libCamera_gc32e1submipiraw_Video_1080_so \
    vendor_lib64_libCamera_gc32e1submipiraw_Video_4k_so \
    vendor_lib64_libCamera_imx782mipiraw_E2EHDR_Preview_so \
    vendor_lib64_libCamera_imx782mipiraw_E2EHDR_Video_so \
    vendor_lib64_libCamera_imx782mipiraw_Face_Capture_so \
    vendor_lib64_libCamera_imx782mipiraw_Flash_Capture_so \
    vendor_lib64_libCamera_imx782mipiraw_HDR_Capture_so \
    vendor_lib64_libCamera_imx782mipiraw_HDR_Preview_so \
    vendor_lib64_libCamera_imx782mipiraw_HDR_Reconfig_Preview_so \
    vendor_lib64_libCamera_imx782mipiraw_HDR_Reconfig_Video_so \
    vendor_lib64_libCamera_imx782mipiraw_HDR_Video_so \
    vendor_lib64_libCamera_imx782mipiraw_N3D_Capture_so \
    vendor_lib64_libCamera_imx782mipiraw_N3D_Preview_so \
    vendor_lib64_libCamera_imx782mipiraw_N3D_Video_so \
    vendor_lib64_libCamera_imx782mipiraw_P1_YUV_so \
    vendor_lib64_libCamera_imx782mipiraw_Scene_Capture_so \
    vendor_lib64_libCamera_imx782mipiraw_Scene_Capture_4cell_so \
    vendor_lib64_libCamera_imx782mipiraw_Scene_Preview_so \
    vendor_lib64_libCamera_imx782mipiraw_Scene_Preview_4k_so \
    vendor_lib64_libCamera_imx782mipiraw_Scene_Preview_ZSD_Flash_so \
    vendor_lib64_libCamera_imx782mipiraw_Video_1080_so \
    vendor_lib64_libCamera_imx782mipiraw_Video_1080_60_so \
    vendor_lib64_libCamera_imx782mipiraw_Video_4k_so \
    vendor_lib64_libDR_so \
    vendor_lib64_libSonyIMX230PdafLibrary_so \
    vendor_lib64_libSonyIMX230PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX338PdafLibrary_so \
    vendor_lib64_libSonyIMX338PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX386PdafLibrary_so \
    vendor_lib64_libSonyIMX386PdafLibraryWrapper_so \
    vendor_lib64_libSonyIMX519PdafLibrary_so \
    vendor_lib64_libSonyIMX519PdafLibraryWrapper_so \
    vendor_lib64_libaaa_ltm_so \
    vendor_lib64_libaaa_ltmx_so \
    vendor_lib64_libaal_cust_func_so \
    vendor_lib64_libaalservice_so \
    vendor_lib64_libacdk_so \
    vendor_lib64_libaiawb_moon_so \
    vendor_lib64_libaiawb_p1ggm_so \
    vendor_lib64_libaiawb_sun_so \
    vendor_lib64_libaibc_tuning_so \
    vendor_lib64_libaibc_tuning_p2_so \
    vendor_lib64_libaibc_tuning_p3_so \
    vendor_lib64_libaibc_tuning_p4_so \
    vendor_lib64_libaidepth_tuning_so \
    vendor_lib64_libaiselector_so \
    vendor_lib64_libcam_afhal_so \
    vendor_lib64_libcam_chdr_so \
    vendor_lib64_libcam_feature_utils_so \
    vendor_lib64_libcam_hal3a_cctsvr_so \
    vendor_lib64_libcam_hal3a_log_so \
    vendor_lib64_libcam_hal3a_v3_ae_so \
    vendor_lib64_libcam_hal3a_v3_ai3a_so \
    vendor_lib64_libcam_hal3a_v3_awb_so \
    vendor_lib64_libcam_hal3a_v3_dng_so \
    vendor_lib64_libcam_hal3a_v3_fsmgr_so \
    vendor_lib64_libcam_hal3a_v3_lscMgr_so \
    vendor_lib64_libcam_hal3a_v3_lsctbl_50_so \
    vendor_lib64_libcam_hal3a_v3_nvram_50_so \
    vendor_lib64_libcam_hal3a_v3_platform_so \
    vendor_lib64_libcam_hal3a_v3_resultpool_so \
    vendor_lib64_libcam_hal3a_v3_so \
    vendor_lib64_libcam_halisp_buf_so \
    vendor_lib64_libcam_halisp_common_so \
    vendor_lib64_libcam_halisp_so \
    vendor_lib64_libcam_halsensor_hwintegration_so \
    vendor_lib64_libcam_halsensor_so \
    vendor_lib64_libcam_iopipe_so \
    vendor_lib64_libcam_isptuning_so \
    vendor_lib64_libcam_pdtblgen_so \
    vendor_lib64_libcam_tuning_cache_so \
    vendor_lib64_libcam_utils_sensorprovider_so \
    vendor_lib64_libcam_vhdr_so \
    vendor_lib64_libcamalgo_ispfeature_so \
    vendor_lib64_libcamalgo_lsc_so \
    vendor_lib64_libcamalgo_platform2_so \
    vendor_lib64_libcamalgo_rotate_so \
    vendor_lib64_libcamalgo_vsf_so \
    vendor_lib64_libcamdrv_isp_so \
    vendor_lib64_libcamdrv_tuning_mgr_so \
    vendor_lib64_libcamdrv_twin_so \
    vendor_lib64_libcamera_custom_pd_buf_mgr_so \
    vendor_lib64_libcamera_customae_so \
    vendor_lib64_libcamera_customaf_so \
    vendor_lib64_libcamera_customawb_so \
    vendor_lib64_libcamera_customflk_so \
    vendor_lib64_libcameracustom_camera_3a_so \
    vendor_lib64_libcameracustom_camera_isp_so \
    vendor_lib64_libcameracustom_camera_sensors_so \
    vendor_lib64_libcameracustom_camera_exif_so \
    vendor_lib64_libcameracustom_eis_so \
    vendor_lib64_libcameracustom_flashlight_so \
    vendor_lib64_libcameracustom_lens_so \
    vendor_lib64_libcameracustom_plugin_so \
    vendor_lib64_libcameracustom_so \
    vendor_lib64_libdip_drv_so \
    vendor_lib64_libdip_postproc_so \
    vendor_lib64_libdpframework_so \
    vendor_lib64_libeffecthal_base_so \
    vendor_lib64_libfeature_face_so \
    vendor_lib64_libfeature_stereo_provider_so \
    vendor_lib64_libfeature_vsdof_hal_so \
    vendor_lib64_libfeature_3dnr_so \
    vendor_lib64_libfeature_eis_so \
    vendor_lib64_libfeature_fsc_so \
    vendor_lib64_libfeature_lmv_so \
    vendor_lib64_libfeature_rss_so \
    vendor_lib64_libfeatureiodrv_mem_so \
    vendor_lib64_libgpudataproducer_so \
    vendor_lib64_libimageio_so \
    vendor_lib64_libimageio_plat_drv_so \
    vendor_lib64_libimageio_plat_pipe_so \
    vendor_lib64_liblpcnr_so \
    vendor_lib64_libmnl_so \
    vendor_lib64_libmsnr_so \
    vendor_lib64_libmtk_drvb_so \
    vendor_lib64_libmtkcam_atmseventmgr_so \
    vendor_lib64_libmtkcam_eventcallback_so \
    vendor_lib64_libmtkcam_featurepipe_capture_so \
    vendor_lib64_libmtkcam_featurepipe_depthmap_so \
    vendor_lib64_libmtkcam_featurepipe_streaming_so \
    vendor_lib64_libmtkcam_featurepipe_vsdof_util_so \
    vendor_lib64_libmtkcam_logicalmodule_so \
    vendor_lib64_libmtkcam_3rdparty_core_so \
    vendor_lib64_libmtkcam_3rdparty_customer_so \
    vendor_lib64_libmtkcam_3rdparty_mtk_so \
    vendor_lib64_libmtkcam_3rdparty_so \
    vendor_lib64_libmtkcam_calibration_convertor_so \
    vendor_lib64_libmtkcam_calibration_provider_so \
    vendor_lib64_libmtkcam_debugutils_so \
    vendor_lib64_libmtkcam_device3_app_so \
    vendor_lib64_libmtkcam_device3_hal_so \
    vendor_lib64_libmtkcam_device3_hidl_so \
    vendor_lib64_libmtkcam_device3_hidlutils_so \
    vendor_lib64_libmtkcam_device3_utils_so \
    vendor_lib64_libmtkcam_devicesessionpolicy_so \
    vendor_lib64_libmtkcam_diputils_so \
    vendor_lib64_libmtkcam_exif_so \
    vendor_lib64_libmtkcam_fdvt_so \
    vendor_lib64_libmtkcam_featurepolicy_so \
    vendor_lib64_libmtkcam_featureutils_so \
    vendor_lib64_libmtkcam_fwkutils_so \
    vendor_lib64_libmtkcam_grallocutils_so \
    vendor_lib64_libmtkcam_hwnode_so \
    vendor_lib64_libmtkcam_hwutils_so \
    vendor_lib64_libmtkcam_imem_so \
    vendor_lib64_libmtkcam_imgbuf_so \
    vendor_lib64_libmtkcam_mapping_mgr_so \
    vendor_lib64_libmtkcam_metadata_so \
    vendor_lib64_libmtkcam_metastore_so \
    vendor_lib64_libmtkcam_mfb_so \
    vendor_lib64_libmtkcam_modulefactory_aaa_so \
    vendor_lib64_libmtkcam_modulefactory_custom_so \
    vendor_lib64_libmtkcam_modulefactory_drv_so \
    vendor_lib64_libmtkcam_modulefactory_utils_so \
    vendor_lib64_libmtkcam_modulehelper_so \
    vendor_lib64_libmtkcam_owe_so \
    vendor_lib64_libmtkcam_pipeline_so \
    vendor_lib64_libmtkcam_pipeline_fbm_so \
    vendor_lib64_libmtkcam_pipelinemodel_so \
    vendor_lib64_libmtkcam_pipelinemodel_adapter_so \
    vendor_lib64_libmtkcam_pipelinemodel_capture_so \
    vendor_lib64_libmtkcam_pipelinemodel_isp_so \
    vendor_lib64_libmtkcam_pipelinemodel_session_so \
    vendor_lib64_libmtkcam_pipelinemodel_utils_so \
    vendor_lib64_libmtkcam_pipelinemodel_zsl_so \
    vendor_lib64_libmtkcam_pipelinepolicy-security_so \
    vendor_lib64_libmtkcam_pipelinepolicy-smvr_so \
    vendor_lib64_libmtkcam_pipelinepolicy_so \
    vendor_lib64_libmtkcam_pipelinepolicy_factory_so \
    vendor_lib64_libmtkcam_prerelease_so \
    vendor_lib64_libmtkcam_rsc_so \
    vendor_lib64_libmtkcam_scenariorecorder_so \
    vendor_lib64_libmtkcam_stdutils_so \
    vendor_lib64_libmtkcam_streamutils_so \
    vendor_lib64_libmtkcam_synchelper_so \
    vendor_lib64_libmtkcam_sysutils_so \
    vendor_lib64_libmtkcam_tuning_utils_so \
    vendor_lib64_libmtkcam_ulog_so \
    vendor_lib64_libneuralnetworks_sl_driver_mtk_prebuilt_so \
    vendor_lib64_libneuron_adapter_mgvi_so \
    vendor_lib64_libneuron_runtime_5_so \
    vendor_lib64_libnir_neon_driver_so \
    vendor_lib64_libpq_cust_base_so \
    vendor_lib64_libpq_prot_so \
    vendor_lib64_libpqparamparser_so \
    vendor_lib64_libstereoinfoaccessor_vsdof_so \
    vendor_lib64_libvainr_model_so \
    vendor_lib64_mtkcam_libmtkcam_streaminfo_plugin-p1stt_so
